# Welcome to Jekyll!
#

# Site settings
title: Atit Shetty
description: |
  <i>Logic will get you from A to B.<br>Imagination will take you everywhere.</i><br/><small>-Albert Einstein</small>
owner: Atit Shetty # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: akshetty@ncsu.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://atitshetty.io" # the base hostname & protocol for your site
landing_page_banner: "images/code3.jpg"
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/AtitShetty
  linkedin-square: https://linkedin.com/in/atit-k-shetty
  facebook-official: https://facebook.com/atit-k-shetty
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email:  mailto:akshetty@ncsu.edu
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
